"""Initial migration

Revision ID: 2009052457d4
Revises: f63e2a9a5b7f
Create Date: 2024-06-22 22:26:51.348891

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2009052457d4'
down_revision = 'f63e2a9a5b7f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('timecards', schema=None) as batch_op:
        batch_op.alter_column('clocked_in',
               existing_type=mysql.DATETIME(),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.alter_column('clocked_out',
               existing_type=mysql.DATETIME(),
               type_=sa.String(length=255),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('timecards', schema=None) as batch_op:
        batch_op.alter_column('clocked_out',
               existing_type=sa.String(length=255),
               type_=mysql.DATETIME(),
               existing_nullable=True)
        batch_op.alter_column('clocked_in',
               existing_type=sa.String(length=255),
               type_=mysql.DATETIME(),
               existing_nullable=True)

    # ### end Alembic commands ###
