"""Initial migration

Revision ID: 9c4044f88609
Revises: a4a57284c003
Create Date: 2024-06-23 01:27:58.728736

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9c4044f88609'
down_revision = 'a4a57284c003'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('timecards', schema=None) as batch_op:
        batch_op.alter_column('date',
               existing_type=mysql.DATETIME(),
               type_=sa.String(length=10),
               existing_nullable=False)
        batch_op.alter_column('clocked_in',
               existing_type=mysql.DATETIME(),
               type_=sa.String(length=5),
               existing_nullable=True)
        batch_op.alter_column('clocked_out',
               existing_type=mysql.DATETIME(),
               type_=sa.String(length=5),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('timecards', schema=None) as batch_op:
        batch_op.alter_column('clocked_out',
               existing_type=sa.String(length=5),
               type_=mysql.DATETIME(),
               existing_nullable=True)
        batch_op.alter_column('clocked_in',
               existing_type=sa.String(length=5),
               type_=mysql.DATETIME(),
               existing_nullable=True)
        batch_op.alter_column('date',
               existing_type=sa.String(length=10),
               type_=mysql.DATETIME(),
               existing_nullable=False)

    # ### end Alembic commands ###
