"""Initial migration

Revision ID: a4a57284c003
Revises: 2009052457d4
Create Date: 2024-06-22 22:30:41.538850

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a4a57284c003'
down_revision = '2009052457d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('timecards', schema=None) as batch_op:
        batch_op.alter_column('date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=False)
        batch_op.alter_column('clocked_in',
               existing_type=mysql.VARCHAR(collation='utf8_unicode_ci', length=255),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.alter_column('clocked_out',
               existing_type=mysql.VARCHAR(collation='utf8_unicode_ci', length=255),
               type_=sa.DateTime(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('timecards', schema=None) as batch_op:
        batch_op.alter_column('clocked_out',
               existing_type=sa.DateTime(),
               type_=mysql.VARCHAR(collation='utf8_unicode_ci', length=255),
               existing_nullable=True)
        batch_op.alter_column('clocked_in',
               existing_type=sa.DateTime(),
               type_=mysql.VARCHAR(collation='utf8_unicode_ci', length=255),
               existing_nullable=True)
        batch_op.alter_column('date',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=False)

    # ### end Alembic commands ###
