"""Initial migration

Revision ID: e3971da930e5
Revises: 10078cf74069
Create Date: 2024-06-22 21:20:44.915759

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3971da930e5'
down_revision = '10078cf74069'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('timecards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('clocked_in', sa.DateTime(), nullable=True),
    sa.Column('clocked_out', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.String(length=150), nullable=True),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name=op.f('fk_timecards_employee_id_employees')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('timecards')
    # ### end Alembic commands ###
